### ISSUE TITLE
재계약률을 평균하는 과정에서 소수점 둘째자리까지 출력되는 이슈 해결

### ISSUE THREAD

**Issue by Woohahalife** [KPT-Final-Team9/back9#110]
## 💬작업 설명

비교 호실의 재계약률을 평균하는 과정에서 소수점 둘째자리까지 출력되는 이슈 해결

## 🔍상세 내용
- [x] : 재계약률 산출 과정에서 발생한 오류 해결

**Comment by kyungho1224** [comment]
자꾸 이슈랑 PR 올라올때마다 외롭지 않아서 좋다
